"""
pages/6_📈_Visualizations.py
==============================
Generates and displays charts using the existing `Visualizer` backend
class. No chart-drawing logic is implemented in this file.
"""

from __future__ import annotations

import streamlit as st

from streamlit_utils import pipeline
from streamlit_utils.ui import inject_global_css, page_header, render_sidebar_status, require_dataset

st.set_page_config(page_title="Visualizations", page_icon="📈", layout="wide")
inject_global_css()
render_sidebar_status()
page_header("📈 Visualizations", "Charts generated by the existing Visualizer backend module.")

require_dataset()
df = st.session_state.df

if "validation_report" not in st.session_state:
    st.info("Visualizations are based on validation results. Running validation now...")
    with st.spinner("Running validation..."):
        st.session_state.validation_report = pipeline.run_validation(df)

report = st.session_state.validation_report

run_clicked = st.button("🎨 Generate Charts", type="primary")

if run_clicked:
    with st.spinner("Generating charts..."):
        st.session_state.chart_paths = pipeline.generate_charts(df, report)
    st.success(f"Generated {len(st.session_state.chart_paths)} chart(s).")

st.divider()

if "chart_paths" not in st.session_state:
    st.info("Click **Generate Charts** to create visualizations for this dataset.")
    st.stop()

chart_paths = st.session_state.chart_paths
charts_by_name = {p.name: p for p in chart_paths}


def _show(name: str, caption: str):
    path = charts_by_name.get(name)
    if path and path.exists():
        st.image(str(path), caption=caption, use_container_width=True)
    else:
        st.info(f"'{caption}' was not generated for this dataset.")


tab_missing, tab_nulls, tab_dupes, tab_dist = st.tabs(
    ["🕳️ Missing Value Heatmap", "📊 Null % Chart", "🧬 Duplicate Summary", "📈 Distributions"]
)

with tab_missing:
    _show("missing_value_heatmap.png", "Missing Value Heatmap")

with tab_nulls:
    _show("null_percentage_bar_chart.png", "Null Percentage by Column")

with tab_dupes:
    _show("duplicate_summary_chart.png", "Duplicate Row Summary")

with tab_dist:
    dist_paths = [p for p in chart_paths if p.name.startswith("distribution_")]
    if not dist_paths:
        st.info("No numeric columns were available for distribution plots.")
    else:
        cols = st.columns(2)
        for i, path in enumerate(dist_paths):
            with cols[i % 2]:
                st.image(str(path), use_container_width=True)

st.divider()
st.page_link("pages/7_📄_Reports.py", label="➡️ Continue to Reports", icon="📄")
